### Conditional Profiles ###
[Anime4K-A]
glsl-shaders-clr
glsl-shaders-append=~~/shaders/Anime4K_Clamp_Highlights.glsl
glsl-shaders-append=~~/shaders/Anime4K_Restore_CNN_VL.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x2.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x4.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl

[Anime4K-B]
glsl-shaders-clr
glsl-shaders-append=~~/shaders/Anime4K_Clamp_Highlights.glsl
glsl-shaders-append=~~/shaders/Anime4K_Restore_CNN_Soft_VL.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x2.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x4.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl

[Anime4K-C]
glsl-shaders-clr
glsl-shaders-append=~~/shaders/Anime4K_Clamp_Highlights.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_VL.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x2.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x4.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl

[Anime4K-AA]
glsl-shaders-clr
glsl-shaders-append=~~/shaders/Anime4K_Clamp_Highlights.glsl
glsl-shaders-append=~~/shaders/Anime4K_Restore_CNN_VL.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl
glsl-shaders-append=~~/shaders/Anime4K_Restore_CNN_M.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x2.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x4.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl

[Anime4K-BB]
glsl-shaders-clr
glsl-shaders-append=~~/shaders/Anime4K_Clamp_Highlights.glsl
glsl-shaders-append=~~/shaders/Anime4K_Restore_CNN_Soft_VL.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x2.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x4.glsl
glsl-shaders-append=~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl

[Anime4K-CA]
glsl-shaders-clr
glsl-shaders-append=~~/shaders/Anime4K_Clamp_Highlights.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_VL.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x2.glsl
glsl-shaders-append=~~/shaders/Anime4K_AutoDownscalePre_x4.glsl
glsl-shaders-append=~~/shaders/Anime4K_Restore_CNN_M.glsl
glsl-shaders-append=~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl

[ArtCNN]
glsl-shaders-clr
glsl-shaders-append=~~/shaders/ArtCNN_C4F16.glsl
