# : Manager [[[

[mgr]
cwd = { fg = "#e4e3d7" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#6ed5bb", bg = "#6ed5bb" }
marker_cut      = { fg = "#bdece0", bg = "#bdece0" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a1d0c5", bg = "#a1d0c5" }

# Count
count_copied   = { fg = "#00201b", bg = "#bdece0" }
count_cut      = { fg = "#00201b", bg = "#bdece0" }
count_selected = { fg = "#2a3400", bg = "#a1d0c5" }

# Border
border_symbol = "│"
border_style  = { fg = "#bece7f" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#bece7f", bold = true, bg = "#13140d" }
inactive  = { fg = "#c4caa8", bg = "#13140d" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#bece7f", fg = "#2a3400", bold = true }
normal_alt  = { bg = "#46483c", fg = "#c7c8b8" }

# Select mode
select_main = { bg = "#c4caa8", fg = "#2e331b", bold = true }
select_alt  = { bg = "#46483c", fg = "#c7c8b8" }

# Unset mode
unset_main = { bg = "#a1d0c5", fg = "#043730", bold = true }
unset_alt  = { bg = "#46483c", fg = "#c7c8b8" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#7e8752" }
perm_write = { fg = "#48907f" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#46caa8" }
perm_sep   = { fg = "#a4c427" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#bece7f", bg = "#393a31" }
progress_error  = { fg = "#ffb4ab", bg = "#393a31" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#393a31" }
cand = { fg = "#bece7f" }
rest = { fg = "#2a3400" }
desc = { fg = "#e4e3d7" }
separator = " ▶ "
separator_style = { fg = "#e4e3d7" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#a1d0c5" }
title_warn  = { fg = "#bece7f" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#bece7f" }
active = { fg = "#a1d0c5", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#bece7f" }
value  = { fg = "#e4e3d7" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#bece7f", bg = "#2a3400" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#bece7f" }
title   = {}
hovered = { fg = "#bdece0", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e4e3d7" }
run    = { fg = "#e4e3d7" }
footer = { fg = "#2e331b", bg = "#c4caa8" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e4e3d7" },
    { url = "*/", fg = "#bece7f" },
]

# : ]]]
