# : Manager [[[

[mgr]
cwd = { fg = "#e0e4db" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#68d2df", bg = "#68d2df" }
marker_cut      = { fg = "#bcebf1", bg = "#bcebf1" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a1ced4", bg = "#a1ced4" }

# Count
count_copied   = { fg = "#001f23", bg = "#bcebf1" }
count_cut      = { fg = "#001f23", bg = "#bcebf1" }
count_selected = { fg = "#083910", bg = "#a1ced4" }

# Border
border_symbol = "│"
border_style  = { fg = "#a0d49b" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#a0d49b", bold = true, bg = "#10140f" }
inactive  = { fg = "#b9ccb4", bg = "#10140f" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#a0d49b", fg = "#083910", bold = true }
normal_alt  = { bg = "#424940", fg = "#c2c9bd" }

# Select mode
select_main = { bg = "#b9ccb4", fg = "#253423", bold = true }
select_alt  = { bg = "#424940", fg = "#c2c9bd" }

# Unset mode
unset_main = { bg = "#a1ced4", fg = "#00363b", bold = true }
unset_alt  = { bg = "#424940", fg = "#c2c9bd" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#678a5e" }
perm_write = { fg = "#458d97" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#3dc5d7" }
perm_sep   = { fg = "#46d636" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#a0d49b", bg = "#363a34" }
progress_error  = { fg = "#ffb4ab", bg = "#363a34" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#363a34" }
cand = { fg = "#a0d49b" }
rest = { fg = "#083910" }
desc = { fg = "#e0e4db" }
separator = " ▶ "
separator_style = { fg = "#e0e4db" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#a1ced4" }
title_warn  = { fg = "#a0d49b" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#a0d49b" }
active = { fg = "#a1ced4", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#a0d49b" }
value  = { fg = "#e0e4db" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#a0d49b", bg = "#083910" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#a0d49b" }
title   = {}
hovered = { fg = "#bcebf1", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e0e4db" }
run    = { fg = "#e0e4db" }
footer = { fg = "#253423", bg = "#b9ccb4" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e0e4db" },
    { url = "*/", fg = "#a0d49b" },
]

# : ]]]
