# : Manager [[[

[mgr]
cwd = { fg = "#dfe3e7" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#9978ff", bg = "#9978ff" }
marker_cut      = { fg = "#e6deff", bg = "#e6deff" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#cac1e9", bg = "#cac1e9" }

# Count
count_copied   = { fg = "#1d1736", bg = "#e6deff" }
count_cut      = { fg = "#1d1736", bg = "#e6deff" }
count_selected = { fg = "#003549", bg = "#cac1e9" }

# Border
border_symbol = "│"
border_style  = { fg = "#8fcef3" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#8fcef3", bold = true, bg = "#0f1417" }
inactive  = { fg = "#b5c9d7", bg = "#0f1417" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#8fcef3", fg = "#003549", bold = true }
normal_alt  = { bg = "#41484d", fg = "#c0c7cd" }

# Select mode
select_main = { bg = "#b5c9d7", fg = "#20333e", bold = true }
select_alt  = { bg = "#41484d", fg = "#c0c7cd" }

# Unset mode
unset_main = { bg = "#cac1e9", fg = "#322c4c", bold = true }
unset_alt  = { bg = "#41484d", fg = "#c0c7cd" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#55809e" }
perm_write = { fg = "#6950c1" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#7245ff" }
perm_sep   = { fg = "#2ba9ff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#8fcef3", bg = "#353a3d" }
progress_error  = { fg = "#ffb4ab", bg = "#353a3d" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#353a3d" }
cand = { fg = "#8fcef3" }
rest = { fg = "#003549" }
desc = { fg = "#dfe3e7" }
separator = " ▶ "
separator_style = { fg = "#dfe3e7" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#cac1e9" }
title_warn  = { fg = "#8fcef3" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#8fcef3" }
active = { fg = "#cac1e9", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#8fcef3" }
value  = { fg = "#dfe3e7" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#8fcef3", bg = "#003549" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#8fcef3" }
title   = {}
hovered = { fg = "#e6deff", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#dfe3e7" }
run    = { fg = "#dfe3e7" }
footer = { fg = "#20333e", bg = "#b5c9d7" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#dfe3e7" },
    { url = "*/", fg = "#8fcef3" },
]

# : ]]]
