module Colors where

data ColorScheme = ColorScheme
  { onSurfaceVariant :: String,
    outline :: String,
    surfaceDim :: String,
    surfaceContainerHighest :: String,
    inverseSurface :: String,
    tertiaryContainer :: String,
    secondaryContainer :: String,
    surfaceContainerLowest :: String,
    surfaceContainerLow :: String,
    surfaceContainerHigh :: String,
    scrim :: String,
    primaryContainer :: String,
    secondary :: String,
    surfaceVariant :: String,
    inverseOnSurface :: String,
    tertiary :: String,
    errorContainer :: String,
    outlineVariant :: String,
    primary :: String,
    onPrimaryContainer :: String,
    errorColor :: String,
    inversePrimary :: String,
    onTertiaryContainer :: String,
    colorRed :: String,
    colorYellow :: String,
    colorGreen :: String
  }

colors :: ColorScheme
colors =
  ColorScheme
    { onSurfaceVariant = "#bec8ca",
      outline = "#899294",
      surfaceDim = "#0e1415",
      surfaceContainerHighest = "#303637",
      inverseSurface = "#dee4e4",
      tertiaryContainer = "#3a4664",
      secondaryContainer = "#324b4e",
      surfaceContainerLowest = "#090f10",
      surfaceContainerLow = "#171d1e",
      surfaceContainerHigh = "#252b2c",
      scrim = "#000000",
      primaryContainer = "#004f57",
      secondary = "#b1cbcf",
      surfaceVariant = "#3f484a",
      inverseOnSurface = "#2b3132",
      tertiary = "#b9c6ea",
      errorContainer = "#93000a",
      outlineVariant = "#3f484a",
      primary = "#81d3df",
      onPrimaryContainer = "#9df0fb",
      errorColor = "#ffb4ab",
      inversePrimary = "#006973",
      onTertiaryContainer = "#d9e2ff",
      colorRed = "#ffb2b9",
      colorYellow = "#b8cf84",
      colorGreen = "#95d5a7"
    }
