module Colors where

data ColorScheme = ColorScheme
  { onSurfaceVariant :: String,
    outline :: String,
    surfaceDim :: String,
    surfaceContainerHighest :: String,
    inverseSurface :: String,
    tertiaryContainer :: String,
    secondaryContainer :: String,
    surfaceContainerLowest :: String,
    surfaceContainerLow :: String,
    surfaceContainerHigh :: String,
    scrim :: String,
    primaryContainer :: String,
    secondary :: String,
    surfaceVariant :: String,
    inverseOnSurface :: String,
    tertiary :: String,
    errorContainer :: String,
    outlineVariant :: String,
    primary :: String,
    onPrimaryContainer :: String,
    errorColor :: String,
    inversePrimary :: String,
    onTertiaryContainer :: String,
    colorRed :: String,
    colorYellow :: String,
    colorGreen :: String
  }

colors :: ColorScheme
colors =
  ColorScheme
    { onSurfaceVariant = "#c0c7cd",
      outline = "#8b9297",
      surfaceDim = "#0f1417",
      surfaceContainerHighest = "#313539",
      inverseSurface = "#dfe3e7",
      tertiaryContainer = "#484264",
      secondaryContainer = "#374955",
      surfaceContainerLowest = "#0a0f12",
      surfaceContainerLow = "#181c1f",
      surfaceContainerHigh = "#262b2e",
      scrim = "#000000",
      primaryContainer = "#004c69",
      secondary = "#b5c9d7",
      surfaceVariant = "#41484d",
      inverseOnSurface = "#2c3134",
      tertiary = "#cac1e9",
      errorContainer = "#93000a",
      outlineVariant = "#41484d",
      primary = "#8fcef3",
      onPrimaryContainer = "#c4e7ff",
      errorColor = "#ffb4ab",
      inversePrimary = "#1c6586",
      onTertiaryContainer = "#e6deff",
      colorRed = "#ffb2b9",
      colorYellow = "#b8cf84",
      colorGreen = "#95d5a7"
    }
