module Colors where

data ColorScheme = ColorScheme
  { onSurfaceVariant :: String,
    outline :: String,
    surfaceDim :: String,
    surfaceContainerHighest :: String,
    inverseSurface :: String,
    tertiaryContainer :: String,
    secondaryContainer :: String,
    surfaceContainerLowest :: String,
    surfaceContainerLow :: String,
    surfaceContainerHigh :: String,
    scrim :: String,
    primaryContainer :: String,
    secondary :: String,
    surfaceVariant :: String,
    inverseOnSurface :: String,
    tertiary :: String,
    errorContainer :: String,
    outlineVariant :: String,
    primary :: String,
    onPrimaryContainer :: String,
    errorColor :: String,
    inversePrimary :: String,
    onTertiaryContainer :: String,
    colorRed :: String,
    colorYellow :: String,
    colorGreen :: String
  }

colors :: ColorScheme
colors =
  ColorScheme
    { onSurfaceVariant = "#c0c8cc",
      outline = "#8a9296",
      surfaceDim = "#0f1417",
      surfaceContainerHighest = "#303638",
      inverseSurface = "#dee3e6",
      tertiaryContainer = "#444465",
      secondaryContainer = "#354a53",
      surfaceContainerLowest = "#0a0f11",
      surfaceContainerLow = "#171c1f",
      surfaceContainerHigh = "#252b2d",
      scrim = "#000000",
      primaryContainer = "#004d62",
      secondary = "#b3cad5",
      surfaceVariant = "#40484c",
      inverseOnSurface = "#2c3134",
      tertiary = "#c4c3eb",
      errorContainer = "#93000a",
      outlineVariant = "#40484c",
      primary = "#89d0ed",
      onPrimaryContainer = "#baeaff",
      errorColor = "#ffb4ab",
      inversePrimary = "#0c6780",
      onTertiaryContainer = "#e2dfff",
      colorRed = "#ffb2b9",
      colorYellow = "#b8cf84",
      colorGreen = "#95d5a7"
    }
