$wallpaper = /home/saumya/dotfiles/wallpapers/Pictures/Wallpapers/3-rain_world.png
$background = 161217
$foreground = e8e0e8

$primary = deb9f7
$secondary = d1c1d9
$tertiary = f4b7bb
$surface = 161217
$surface_bright = 3c383e
$outline = 968e98
$error = 000000

$shadow = 000000

$red = ffb2b9
$green = 95d5a7
$yellow = dec56e
$blue = cebdfe
$magenta = e8b6f0
$cyan = 82d3e2
$white = 82d3e0
$red_dim = 000000
$green_dim = 000000
$yellow_dim = 000000
$blue_dim = 000000
$magenta_dim = 000000
$cyan_dim = 000000
