$wallpaper = /home/saumya/Pictures/Wallpapers/l11ppyt.jpeg
$background = 0e1415
$foreground = dde4e3

$primary = 80d4d8
$secondary = b1cccd
$tertiary = b5c7e9
$surface = 0e1415
$surface_bright = 343a3b
$outline = 899393
$error = 000000

$shadow = 000000

$red = ffb595
$green = 95d5a7
$yellow = b8cf84
$blue = afc6ff
$magenta = e4b7f3
$cyan = 80d4d6
$white = 82d3e0
$red_dim = 000000
$green_dim = 000000
$yellow_dim = 000000
$blue_dim = 000000
$magenta_dim = 000000
$cyan_dim = 000000
