$wallpaper = /home/saumya/Pictures/Wallpapers/mc_wallpaper_movie_vista_2560x1440.png
$background = 0f1417
$foreground = dfe3e7

$primary = 8ecff2
$secondary = b5c9d7
$tertiary = c9c2ea
$surface = 0f1417
$surface_bright = 353a3d
$outline = 8a9297
$error = 000000

$shadow = 000000

$red = ffb2b9
$green = 95d5a7
$yellow = b8cf84
$blue = afc6ff
$magenta = e4b7f3
$cyan = 82d3e2
$white = 82d3e0
$red_dim = 000000
$green_dim = 000000
$yellow_dim = 000000
$blue_dim = 000000
$magenta_dim = 000000
$cyan_dim = 000000
