source=~/.config/hypr/configs/animations/animations-end4.conf
source=~/.config/hypr/configs/misc.conf
source=~/.config/hypr/configs/layouts.conf
source=~/.config/hypr/configs/keybinds.conf
source=~/.config/hypr/configs/input.conf
# source=~/.config/hypr/configs/env_default.conf
# source=~/.config/hypr/configs/env_nvidia.conf
source=~/.config/hypr/configs/exec.conf
source=~/.config/hypr/configs/monitors.conf
source=~/.config/hypr/configs/plugins.conf
source=~/.config/hypr/configs/rules.conf
source=~/.config/hypr/configs/dec-2.conf
source=/home/saumya/.config/ignis/assets/hypr/blur.conf

# exec-once = ambxst
