module Colors where

data ColorScheme = ColorScheme
  { onSurfaceVariant :: String,
    outline :: String,
    surfaceDim :: String,
    surfaceContainerHighest :: String,
    inverseSurface :: String,
    tertiaryContainer :: String,
    secondaryContainer :: String,
    surfaceContainerLowest :: String,
    surfaceContainerLow :: String,
    surfaceContainerHigh :: String,
    scrim :: String,
    primaryContainer :: String,
    secondary :: String,
    surfaceVariant :: String,
    inverseOnSurface :: String,
    tertiary :: String,
    errorContainer :: String,
    outlineVariant :: String,
    primary :: String,
    onPrimaryContainer :: String,
    errorColor :: String,
    inversePrimary :: String,
    onTertiaryContainer :: String,
    colorRed :: String,
    colorYellow :: String,
    colorGreen :: String
  }

colors :: ColorScheme
colors =
  ColorScheme
    { onSurfaceVariant = "#cec3cd",
      outline = "#988e97",
      surfaceDim = "#161217",
      surfaceContainerHighest = "#383339",
      inverseSurface = "#e9e0e7",
      tertiaryContainer = "#663b39",
      secondaryContainer = "#514254",
      surfaceContainerLowest = "#110d12",
      surfaceContainerLow = "#1f1a1f",
      surfaceContainerHigh = "#2d282e",
      scrim = "#000000",
      primaryContainer = "#5d386b",
      secondary = "#d5c0d7",
      surfaceVariant = "#4c444d",
      inverseOnSurface = "#342f34",
      tertiary = "#f5b7b4",
      errorContainer = "#93000a",
      outlineVariant = "#4c444d",
      primary = "#e5b6f2",
      onPrimaryContainer = "#f8d8ff",
      errorColor = "#ffb4ab",
      inversePrimary = "#765084",
      onTertiaryContainer = "#ffdad8",
      colorRed = "#ffb2b9",
      colorYellow = "#dec56e",
      colorGreen = "#95d5a7"
    }
