module Colors where

data ColorScheme = ColorScheme
  { onSurfaceVariant :: String,
    outline :: String,
    surfaceDim :: String,
    surfaceContainerHighest :: String,
    inverseSurface :: String,
    tertiaryContainer :: String,
    secondaryContainer :: String,
    surfaceContainerLowest :: String,
    surfaceContainerLow :: String,
    surfaceContainerHigh :: String,
    scrim :: String,
    primaryContainer :: String,
    secondary :: String,
    surfaceVariant :: String,
    inverseOnSurface :: String,
    tertiary :: String,
    errorContainer :: String,
    outlineVariant :: String,
    primary :: String,
    onPrimaryContainer :: String,
    errorColor :: String,
    inversePrimary :: String,
    onTertiaryContainer :: String,
    colorRed :: String,
    colorYellow :: String,
    colorGreen :: String
  }

colors :: ColorScheme
colors =
  ColorScheme
    { onSurfaceVariant = "#d7c3b8",
      outline = "#9f8d83",
      surfaceDim = "#19120d",
      surfaceContainerHighest = "#3d332d",
      inverseSurface = "#f0dfd7",
      tertiaryContainer = "#48491e",
      secondaryContainer = "#5b4130",
      surfaceContainerLowest = "#140d08",
      surfaceContainerLow = "#221a15",
      surfaceContainerHigh = "#312823",
      scrim = "#000000",
      primaryContainer = "#6e390f",
      secondary = "#e5bfa9",
      surfaceVariant = "#52443c",
      inverseOnSurface = "#382e29",
      tertiary = "#caca93",
      errorContainer = "#93000a",
      outlineVariant = "#52443c",
      primary = "#ffb688",
      onPrimaryContainer = "#ffdbc7",
      errorColor = "#ffb4ab",
      inversePrimary = "#8b4f24",
      onTertiaryContainer = "#e6e6ad",
      colorRed = "#ffb599",
      colorYellow = "#dec56e",
      colorGreen = "#b7d085"
    }
