module Colors where

data ColorScheme = ColorScheme
  { onSurfaceVariant :: String,
    outline :: String,
    surfaceDim :: String,
    surfaceContainerHighest :: String,
    inverseSurface :: String,
    tertiaryContainer :: String,
    secondaryContainer :: String,
    surfaceContainerLowest :: String,
    surfaceContainerLow :: String,
    surfaceContainerHigh :: String,
    scrim :: String,
    primaryContainer :: String,
    secondary :: String,
    surfaceVariant :: String,
    inverseOnSurface :: String,
    tertiary :: String,
    errorContainer :: String,
    outlineVariant :: String,
    primary :: String,
    onPrimaryContainer :: String,
    errorColor :: String,
    inversePrimary :: String,
    onTertiaryContainer :: String,
    colorRed :: String,
    colorYellow :: String,
    colorGreen :: String
  }

colors :: ColorScheme
colors =
  ColorScheme
    { onSurfaceVariant = "#c5c6d0",
      outline = "#8f9099",
      surfaceDim = "#121318",
      surfaceContainerHighest = "#33353a",
      inverseSurface = "#e2e2e9",
      tertiaryContainer = "#593d5a",
      secondaryContainer = "#404659",
      surfaceContainerLowest = "#0c0e13",
      surfaceContainerLow = "#1a1b20",
      surfaceContainerHigh = "#282a2f",
      scrim = "#000000",
      primaryContainer = "#2e4578",
      secondary = "#c0c6dc",
      surfaceVariant = "#44464f",
      inverseOnSurface = "#2f3036",
      tertiary = "#e0bbdd",
      errorContainer = "#93000a",
      outlineVariant = "#44464f",
      primary = "#b0c6ff",
      onPrimaryContainer = "#d9e2ff",
      errorColor = "#ffb4ab",
      inversePrimary = "#475d92",
      onTertiaryContainer = "#fdd7fa",
      colorRed = "#ffb2b9",
      colorYellow = "#b8cf84",
      colorGreen = "#95d5a7"
    }
