lxc.include = /etc/lxc/includes/configpacks/xorg.conf
lxc.include = /etc/lxc/includes/configpacks/nvidia.conf
lxc.include = /etc/lxc/includes/configpacks/pacman.conf
lxc.include = /etc/lxc/includes/configpacks/desktop.conf
lxc.mount.entry = /run/media/saumya/tank/games/ home/trix/Games none bind,create=dir,idmap=container 0 0



# Allow the Input (13), HID (243), and uinput (10) Major numbers
lxc.cgroup2.devices.allow = c 13:* rwm
lxc.cgroup2.devices.allow = c 243:* rwm
lxc.cgroup2.devices.allow = c 10:223 rwm

# Enable autodev (Required to populate /dev in the container)
lxc.autodev = 1

# Mount the Joystick nodes via ID
lxc.mount.entry = /dev/input/by-id/usb-8BitDo_8BitDo_Ultimate_2C_Wired_Controller_F1D50C77A1-event-joystick dev/input/event31 none bind,optional,create=file
lxc.mount.entry = /dev/input/by-id/usb-8BitDo_8BitDo_Ultimate_2C_Wired_Controller_F1D50C77A1-joystick dev/input/js0 none bind,optional,create=file

# Mount uinput (The controller won't work in-game without this)
lxc.mount.entry = /dev/uinput dev/uinput none bind,optional,create=file
lxc.mount.entry = /proc/acpi/call proc/acpi/call none bind,create=file 0 0
