lxc.include = /etc/lxc/includes/configpacks/xorg.conf
lxc.include = /etc/lxc/includes/configpacks/nvidia.conf
lxc.include = /etc/lxc/includes/configpacks/pacman.conf
lxc.include = /etc/lxc/includes/configpacks/desktop.conf

