lxc.mount.entry = /home/saumya/dotfiles home/trix/dotfiles none bind,optional,create=dir,ro,idmap=container 0 0
# DISCORD RPC
lxc.mount.entry = /run/user/1000/discord-ipc-0 run/user/1000/discord-ipc-0 none bind,optional,create=file,rw 0 0
