lxc.mount.entry = /home/saumya/dotfiles home/saumya/dotfiles none bind,optional,create=dir,ro 0 0
# DISCORD RPC
lxc.environment = XDG_RUNTIME_DIR=/user/1000
lxc.mount.entry = /run/user/1000/discord-ipc-0 user/1000/discord-ipc-0 none bind,optional,create=file,rw 0 0
