# NVIDIA device nodes
lxc.mount.entry = /dev/nvidia0 dev/nvidia0 none bind,optional,create=file 0 0
lxc.mount.entry = /dev/nvidiactl dev/nvidiactl none bind,optional,create=file 0 0
lxc.mount.entry = /dev/nvidia-modeset dev/nvidia-modeset none bind,optional,create=file 0 0
lxc.mount.entry = /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file 0 0
lxc.mount.entry = /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file 0 0
lxc.mount.entry = /dev/nvidia-caps dev/nvidia-caps none bind,optional,create=dir 0 0
# Allow DRI devices (Major 226)

# Mount DRI nodes
lxc.mount.entry = /dev/dri dev/dri none bind,optional,create=dir 0 0

# Allow NVIDIA char devices - Needed
lxc.cgroup2.devices.allow = c 226:* rwm
lxc.cgroup2.devices.allow = c 195:* rwm
lxc.cgroup2.devices.allow = c 237:* rwm
lxc.cgroup2.devices.allow = c 240:* rwm

