# lxc.mount.entry = /etc/pacman.d/ etc/pacman.d/ none bind,optional,create=dir,ro,idmap=container 0 0
# lxc.mount.entry = /etc/pacman.conf etc/pacman.conf none bind,optional,create=file,ro,idmap=container 0 0
