lxc.mount.entry = tmpfs tmp tmpfs defaults
# Display
lxc.mount.entry = /tmp/.X11-unix tmp/.X11-unix none bind,optional,create=dir,ro
lxc.environment = DISPLAY=:0
# Audio
lxc.environment = PULSE_SERVER=10.0.3.1:4656
