# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#dfe3e7"

# Title color for boxes
theme[title]="#8fcef3"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b5c9d7"

# Background color of selected item in processes box
theme[selected_bg]="#8fcef3"

# Foreground color of selected item in processes box
theme[selected_fg]="#003549"

# Color of inactive/disabled text
theme[inactive_fg]="#c0c7cd"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#cac1e9"

# Cpu box outline color
theme[cpu_box]="#8b9297"

# Memory/disks box outline color
theme[mem_box]="#8b9297"

# Net up/down box outline color
theme[net_box]="#8b9297"

# Processes box outline color
theme[proc_box]="#8b9297"

# Box divider line and small boxes line color
theme[div_line]="#41484d"

# Temperature graph colors
theme[temp_start]="#b5c9d7"
theme[temp_mid]="#8fcef3"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#b5c9d7"
theme[cpu_mid]="#8fcef3"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#b5c9d7"
theme[free_mid]=""
theme[free_end]="#374955"

# Mem/Disk cached meter
theme[cached_start]="#cac1e9"
theme[cached_mid]=""
theme[cached_end]="#484264"

# Mem/Disk available meter
theme[available_start]="#8fcef3"
theme[available_mid]=""
theme[available_end]="#004c69"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#b5c9d7"
theme[download_mid]="#8fcef3"
theme[download_end]="#cac1e9"

# Upload graph colors
theme[upload_start]="#b5c9d7"
theme[upload_mid]="#8fcef3"
theme[upload_end]="#cac1e9"
