# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#f0dfd7"

# Title color for boxes
theme[title]="#ffb688"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e5bfa9"

# Background color of selected item in processes box
theme[selected_bg]="#ffb688"

# Foreground color of selected item in processes box
theme[selected_fg]="#512400"

# Color of inactive/disabled text
theme[inactive_fg]="#d7c3b8"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#caca93"

# Cpu box outline color
theme[cpu_box]="#9f8d83"

# Memory/disks box outline color
theme[mem_box]="#9f8d83"

# Net up/down box outline color
theme[net_box]="#9f8d83"

# Processes box outline color
theme[proc_box]="#9f8d83"

# Box divider line and small boxes line color
theme[div_line]="#52443c"

# Temperature graph colors
theme[temp_start]="#e5bfa9"
theme[temp_mid]="#ffb688"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#e5bfa9"
theme[cpu_mid]="#ffb688"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#e5bfa9"
theme[free_mid]=""
theme[free_end]="#5b4130"

# Mem/Disk cached meter
theme[cached_start]="#caca93"
theme[cached_mid]=""
theme[cached_end]="#48491e"

# Mem/Disk available meter
theme[available_start]="#ffb688"
theme[available_mid]=""
theme[available_end]="#6e390f"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#e5bfa9"
theme[download_mid]="#ffb688"
theme[download_end]="#caca93"

# Upload graph colors
theme[upload_start]="#e5bfa9"
theme[upload_mid]="#ffb688"
theme[upload_end]="#caca93"
