# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e0e4db"

# Title color for boxes
theme[title]="#a0d49b"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b9ccb4"

# Background color of selected item in processes box
theme[selected_bg]="#a0d49b"

# Foreground color of selected item in processes box
theme[selected_fg]="#083910"

# Color of inactive/disabled text
theme[inactive_fg]="#c2c9bd"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a1ced4"

# Cpu box outline color
theme[cpu_box]="#8c9388"

# Memory/disks box outline color
theme[mem_box]="#8c9388"

# Net up/down box outline color
theme[net_box]="#8c9388"

# Processes box outline color
theme[proc_box]="#8c9388"

# Box divider line and small boxes line color
theme[div_line]="#424940"

# Temperature graph colors
theme[temp_start]="#b9ccb4"
theme[temp_mid]="#a0d49b"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#b9ccb4"
theme[cpu_mid]="#a0d49b"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#b9ccb4"
theme[free_mid]=""
theme[free_end]="#3b4b39"

# Mem/Disk cached meter
theme[cached_start]="#a1ced4"
theme[cached_mid]=""
theme[cached_end]="#1f4d52"

# Mem/Disk available meter
theme[available_start]="#a0d49b"
theme[available_mid]=""
theme[available_end]="#235024"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#b9ccb4"
theme[download_mid]="#a0d49b"
theme[download_end]="#a1ced4"

# Upload graph colors
theme[upload_start]="#b9ccb4"
theme[upload_mid]="#a0d49b"
theme[upload_end]="#a1ced4"
