# Default monitor mode
# monitor = , 1920x1080@165,0x0,1
monitorv2{
    output = eDP-1
    mode = 1920x1080@165.01
    position = 0x0
    scale = 1
    vrr = 0
    supports_hdr = 0
    supports_wide_color= 1
    sdr_min_luminance = 0.005
    sdr_max_luminance = 250
}

monitorv2 {
  output = HDMI-A-1
  mode = 1360x768@59.8
  position = 2332x756
  scale = 1
}
# monitor = DP-3, 1920x1080@75,1920x0,1,mirror,eDP-1

render {
    cm_auto_hdr = 1
    direct_scanout = 2
}
