[config]
reload_apps = true

[config.reload_apps_list]
gtk_theme = true

[config.wallpaper]
set = true
command = "feh --bg-fill {{ image }} && betterlockscreen -u {{ image }} &"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty"
output_path = "~/.config/ghostty/themes/matugen"

[templates.gradience]
input_path = "~/.config/matugen/templates/gradience.json"
output_path = "~/.config/presets/user/gradience.json"
post_hook = "gradience-cli apply --gtk both -n Matu-Adw"

[templates.discord]
input_path = "~/.config/matugen/templates/discord-material-you.theme.css"
output_path = "~/.config/Equicord/themes/material-you.theme.css"

[templates.pywaljson]
input_path = "~/.config/matugen/templates/pywal-colors.json"
output_path = "~/.cache/wal/colors.json"
post_hook = "pywalfox update &"

[templates.zathura]
input_path = "~/.config/matugen/templates/colors-zathura"
output_path = "~/.config/zathura/zathurarc"

[templates.yazi]
input_path = "~/.config/matugen/templates/yazi-theme.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.ini"
output_path = "~/.config/fuzzel/fuzzel.ini"

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'


[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae-matugen.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

[templates.xmobar]
input_path = '~/.config/matugen/templates/Colors.hs'
output_path = '~/.config/xmobar/lib/Colors.hs'
index = 0

[templates.xmonad]
index = 1
input_path = '~/.config/matugen/templates/Colors.hs'
output_path = '~/.config/xmonad/lib/Colors.hs'
post_hook = 'xmonad --recompile && xmonad --restart'

[templates.spotify]
input_path = '~/.config/matugen/templates/spotify.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
post_hook = 'spicetify apply'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

[config.custom_colors.orange]
color = "#FFA500"
blend = true

[config.custom_colors.purple]
color = "#800080"
blend = true

[config.custom_colors.teal]
color = "#008080"
blend = true

[config.custom_colors.pink]
color = "#FFC0CB"
blend = true

[config.custom_colors.brown]
color = "#A52A2A"
blend = true

# [templates.rewaita]
# input_path = '~/.config/matugen/templates/matugen 😎.css'
# output_path = '~/.local/share/dark/Matugen 😎.css'
